<?php
/**
 * @file
 * Base module file for xml_field_codemirror
 *
 * @defgroup xml_field_codemirror CodeMirror XML Widget
 * @{
 */

/**
 * @var XML_FIELD_CODEMIRROR_DEFAULT_THEME
 */
define('XML_FIELD_CODEMIRROR_DEFAULT_THEME', 'default');

/**
 * Return the default settings for CodeMirror
 *
 * @return array()
 */
function _xml_field_codemirror_options() {
  $options = array(
    'htmlMode' => FALSE,
    'alignCDATA' => TRUE,
    'lineNumbers' => TRUE,
    'lineWrapping' => TRUE,
    'tabsize' => 2,
    'mode' => 'xml',
    'theme' => XML_FIELD_CODEMIRROR_DEFAULT_THEME,
    'autoCloseTags' => 'true',
  );
  drupal_alter('xml_field_codemirror_config', $options);
  return $options;
}

/**
 * Implements hook_xml_field_codemirror_config_alter()
 *
 * Allow modules to alter the codemirror configuration options. Note that field
   instance options (set in the UI) take precendence over any values here; these
   are just global defaults.
 *
 * @see http://codemirror.net/doc/manual.html
 */
function xml_field_codemirror_xml_field_codemirror_instance_config_alter(&$config, $field, $instance) {
  // Set the global default to be 'cobalt' instead of 'default'
  $config['theme'] = 'cobalt';
  $config['lineNumbers'] = TRUE;
}

/**
 * Implements hook_field_widget_info().
 */
function xml_field_codemirror_field_widget_info() {
  return array(
    'xml_field_codemirror' => array(
      'label' => t('CodeMirror XML'),
      'field types' => array('xml_field_xml'),
      'settings' => array(
        'cm' => _xml_field_codemirror_options(),
      ),
      'behaviors' => array(
        'multiple values' => FIELD_BEHAVIOR_DEFAULT,
        'default value' => FIELD_BEHAVIOR_DEFAULT,
      ),
    ),
  );
}

/**
 * Implements hook_field_widget_settings_form().
 */
function xml_field_codemirror_field_widget_settings_form($field, $instance) {
  $widget = $instance['widget'];
  $settings = $widget['settings'];
  $settings['cm'] = array_filter($settings['cm']) + _xml_field_codemirror_options();
  $form = array();
  if ($widget['type'] == 'xml_field_codemirror') {
    $form['cm']['theme'] = array(
      '#type' => 'select',
      '#title' => t('Theme'),
      '#description' => t('Demo these themes <a href="@url" onclick="window.open(this.href); return false;">here</a>.', array(
        '@url' => 'http://codemirror.net/demo/theme.html',
      )),
      '#default_value' => $settings['cm']['theme'],
      '#required' => TRUE,
      '#options' => _xml_field_codemirror_get_available_themes(),

      // Stuck on this hiding for now
      //'#ajax' => array(
      //  'callback' => '_xml_field_codemirror_theme_demo',
      //  'event' => 'change',
      //  'wrapper' => 'edit-field-xml-metadata',
      //  'method' => 'replace',
      //  'effect' => 'fade',
      //),
    );
    //$form['rows'] = array(
    //  '#type' => 'textfield',
    //  '#title' => t('Rows'),
    //  '#default_value' => $settings['rows'],
    //  '#element_validate' => array('_element_validate_integer_positive'),
    //  '#required' => TRUE,
    //);
    //$form['autoresize'] = array(
    //  '#type' => 'checkbox',
    //  '#title' => t('Autoresize'),
    //  '#default_value' => $settings['autoresize'],
    //);
  }
  return $form;
}

/**
 * Return the HTML for the theme demo
 *
 * @return array();
 */
//function _xml_field_codemirror_theme_demo($form, $form_state) {
//
//  $field = $form['#field']['field_name'];
//  $replace = $form['instance']['default_value_widget'][$field];
//  //$replace = $form['instance']['default_value_widget'];
//  $theme = $form_state['values']['instance']['widget']['settings']['cm']['theme'];
//  $replace['und'][0]['#attached']['js'][0]['data']['XMLFieldCodeMirror'][0]['theme'] = $theme;
//  //$replace[$field]['und'][0]['#attached']['js'][0]['data']['XMLFieldCodeMirror'][0]['theme'] = $theme;
//  return $replace;
//}

/**
 * Implements hook_field_widget_form().
 */
function xml_field_codemirror_field_widget_form(&$form, &$form_state, $field, $instance, $langcode, $items, $delta, $element) {
  $settings = array(
    $delta => array_filter($instance['widget']['settings']['cm']) + _xml_field_codemirror_options(),
  );

  $main_widget = $element + array(
    '#type' => 'textarea',
    '#default_value' => isset($items[$delta]['xml']) ? $items[$delta]['xml'] : '',
    '#resizable' => FALSE,
    '#attached' => array(
      'js' => array(
        array(
          'data' => libraries_get_path('codemirror') . '/lib/codemirror.js',
          'weight' => -10,
        ),
        array(
          'data' => libraries_get_path('codemirror') . '/addon/hint/show-hint.js',
          'weight' => -9,
        ),
        array(
          'data' => libraries_get_path('codemirror') . '/addon/edit/closetag.js',
          'weight' => -8,
        ),
        array(
          'data' => libraries_get_path('codemirror') . '/addon/hint/xml-hint.js',
          'weight' => -7,
        ),
        drupal_get_path('module', 'xml_field_codemirror') . '/xml_field_codemirror.js',
      ),
      'css' => array(
        libraries_get_path('codemirror') . '/lib/codemirror.css',
        libraries_get_path('codemirror') . '/addon/hint-show-hint.css',
        drupal_get_path('module', 'xml_field_codemirror') . '/xml_field_codemirror.css',
      ),
    ),
  );
  $main_widget['#attributes']['class'][] = 'xml-field-codemirror';
  $element['#attached']['js'][] = array(
    'data' => array('XMLFieldCodeMirror' => $settings),
    'type' => 'setting',
  );
  $theme = $settings[$delta]['theme'];
  if ($theme != 'default') {
    $main_widget['#attached']['css'][] = array(
      'data' => libraries_get_path('codemirror') . "/theme/{$theme}.css",
      'type' => 'file',
    );
  }
  $mode = $settings[$delta]['mode'];
  $main_widget['#attached']['js'][] = array(
    'data' => libraries_get_path('codemirror') . "/mode/{$mode}/{$mode}.js",
    'type' => 'file',
    'weight' => '10',
  );
  $element['xml'] = $main_widget;

  return $element;
}

/**
 * Returns all available codemirror themes
 *
 * courtesy of http://drupal.org/project/codemirror
 *
 * @return array
 *   keys and values are the themes
 */
function _xml_field_codemirror_get_available_themes() {
  $themes = file_scan_directory(libraries_get_path('codemirror') . '/theme',
    '/\.css/', array('key' => 'name'));
  foreach ($themes as $name => $theme) {
    $themes[$name] = $name;
  }
  $themes = array('default' => 'default') + $themes;
  ksort($themes);
  return $themes;
}

/**
 * Return information about external libraries.
 *
 * @return
 *   An associative array whose keys are internal names of libraries and whose
 *   values are describing each library. Each key is the directory name below
 *   the 'libraries' directory, in which the library may be found. Each value is
 *   an associative array containing:
 *   - name: The official, human-readable name of the library.
 *   - vendor url: The URL of the homepage of the library.
 *   - download url: The URL of a web page on which the library can be obtained.
 *   - path: (optional) A relative path from the directory of the library to the
 *     actual library. Only required if the extracted download package contains
 *     the actual library files in a sub-directory.
 *   - library path: (optional) The absolute path to the library directory. This
 *     should not be declared normally, as it is automatically detected, to
 *     allow for multiple possible library locations. A valid use-case is an
 *     external library, in which case the full URL to the library should be
 *     specified here.
 *   - version: (optional) The version of the library. This should not be
 *     declared normally, as it is automatically detected (see 'version
 *     callback' below) to allow for version changes of libraries without code
 *     changes of implementing modules and to support different versions of a
 *     library simultaneously (though only one version can be installed per
 *     site). A valid use-case is an external library whose version cannot be
 *     determined programatically.
 *   - version callback: (optional) The name of a function that detects and
 *     returns the full version string of the library. The first argument is
 *     always $library, an array containing all library information as described
 *     here. There are two ways to declare the version callback's additional
 *     arguments, either as a single $options parameter or as multiple
 *     parameters, which correspond to the two ways to specify the argument
 *     values (see 'version arguments'). Defaults to libraries_get_version().
 *   - version arguments: A list of arguments to pass to the version callback.
 *     Version arguments can be declared either as an associative array whose
 *     keys are the argument names or as an indexed array without specifying
 *     keys. If declared as an associative array, the arguments get passed to
 *     the version callback as a single $options parameter whose keys are the
 *     argument names (i.e. $options is identical to the specified array). If
 *     declared as an indexed array, the array values get passed to the version
 *     callback as seperate arguments in the order they were declared. The
 *     default version callback libraries_get_version() expects a single,
 *     associative array with named keys:
 *     - file: The filename to parse for the version, relative to the library
 *       path. For example: 'docs/changelog.txt'.
 *     - pattern: A string containing a regular expression (PCRE) to match the
 *       library version. For example: '@version\s+([0-9a-zA-Z\.-]+)@'. Note
 *       that the returned version is not the match of the entire pattern (i.e.
 *       '@version 1.2.3' in the above example) but the match of the first
 *       sub-pattern (i.e. '1.2.3' in the above example).
 *     - lines: (optional) The maximum number of lines to search the pattern in.
 *       Defaults to 20.
 *     - cols: (optional) The maximum number of characters per line to take into
 *       account. Defaults to 200. In case of minified or compressed files, this
 *       prevents reading the entire file into memory.
 *   - files: An associative array of library files to load. Supported keys are:
 *     - js: A list of JavaScript files to load, using the same syntax as Drupal
 *       core's hook_library().
 *     - css: A list of CSS files to load, using the same syntax as Drupal
 *       core's hook_library().
 *     - php: A list of PHP files to load.
 *   - dependencies: An array of libraries this library depends on. Similar to
 *     declaring module dependencies, the dependency declaration may contain
 *     information on the supported version. Examples of supported declarations:
 *     @code
 *     $libraries['dependencies'] = array(
 *       // Load the 'example' library, regardless of the version available:
 *       'example',
 *       // Only load the 'example' library, if version 1.2 is available:
 *       'example (1.2)',
 *       // Only load a version later than 1.3-beta2 of the 'example' library:
 *       'example (>1.3-beta2)'
 *       // Only load a version equal to or later than 1.3-beta3:
 *       'example (>=1.3-beta3)',
 *       // Only load a version earlier than 1.5:
 *       'example (<1.5)',
 *       // Only load a version equal to or earlier than 1.4:
 *       'example (<=1.4)',
 *       // Combinations of the above are allowed as well:
 *       'example (>=1.3-beta2, <1.5)',
 *     );
 *     @endcode
 *   - variants: (optional) An associative array of available library variants.
 *     For example, the top-level 'files' property may refer to a default
 *     variant that is compressed. If the library also ships with a minified and
 *     uncompressed/source variant, those can be defined here. Each key should
 *     describe the variant type, e.g. 'minified' or 'source'. Each value is an
 *     associative array of top-level properties that are entirely overridden by
 *     the variant, most often just 'files'. Additionally, each variant can
 *     contain following properties:
 *     - variant callback: (optional) The name of a function that detects the
 *       variant and returns TRUE or FALSE, depending on whether the variant is
 *       available or not. The first argument is always $library, an array
 *       containing all library information as described here. The second
 *       argument is always a string containing the variant name. There are two
 *       ways to declare the variant callback's additinal arguments, either as a
 *       single $options parameter or as multiple parameters, which correspond
 *       to the two ways to specify the argument values (see 'variant
 *       arguments'). If ommitted, the variant is expected to always be
 *       available.
 *     - variant arguments: A list of arguments to pass to the variant callback.
 *       Variant arguments can be declared either as an associative array whose
 *       keys are the argument names or as an indexed array without specifying
 *       keys. If declared as an associative array, the arguments get passed to
 *       the variant callback as a single $options parameter whose keys are the
 *       argument names (i.e. $options is identical to the specified array). If
 *       declared as an indexed array, the array values get passed to the
 *       variant callback as seperate arguments in the order they were declared.
 *     Variants can be version-specific (see 'versions').
 *   - versions: (optional) An associative array of supported library versions.
 *     Naturally, libraries evolve over time and so do their APIs. In case a
 *     library changes between versions, different 'files' may need to be
 *     loaded, different 'variants' may become available, or Drupal modules need
 *     to load different integration files adapted to the new version. Each key
 *     is a version *string* (PHP does not support floats as keys). Each value
 *     is an associative array of top-level properties that are entirely
 *     overridden by the version.
 *   - integration files: (optional) An associative array whose keys are module
 *     names and whose values are sets of files to load for the module, using
 *     the same notion as the top-level 'files' property. Each specified file
 *     should contain the path to the file relative to the module it belongs to.
 *   - callbacks: An associative array whose keys are callback groups and whose
 *     values are arrays of callbacks to apply to the library in that group.
 *     Each callback receives the following arguments:
 *     - $library: An array of library information belonging to the top-level
 *       library, a specific version, a specific variant or a specific variant
 *       of a specific version. Because library information such as the 'files'
 *       property (see above) can be declared in all these different locations
 *       of the library array, but a callback may have to act on all these
 *       different parts of the library, it is called recursively for each
 *       library with a certain part of the libraries array passed as $library
 *       each time.
 *     - $version: If the $library array belongs to a certain version (see
 *       above), a string containing the version. This argument may be empty, so
 *       NULL should be specified as the default value.
 *     - $variant: If the $library array belongs to a certain variant (see
 *       above), a string containing the variant name. This argument may be
 *       empty, so NULL should be specified as the default value.
 *     Valid callback groups are:
 *     - info: Callbacks registered in this group are applied after the library
 *       information has been retrieved via hook_libraries_info() or info files.
 *     - pre-detect: Callbacks registered in this group are applied after the
 *       library path has been determined and before the version callback is
 *       invoked. At this point the following additional information is available:
 *       - $library['library path']: The path on the file system to the library.
 *     - post-detect: Callbacks registered in this group are applied after the
 *       library has been successfully detected. At this point the library
 *       contains the version-specific information, if specified, and following
 *       additional information is available:
 *       - $library['installed']: A boolean indicating whether the library is
 *         installed or not.
 *       - $library['version']: If it could be detected, a string containing the
 *         version of the library.
 *       - $library['variants'][$variant]['installed']: For each specified
 *         variant, a boolean indicating whether the variant is installed or
 *         not.
 *       Note that in this group the 'versions' property is no longer available.
 *     - pre-load: Callbacks registered in this group are applied directly
 *       before this library is loaded. At this point the library contains
 *       variant-specific information, if specified. Note that in this group the
 *       'variants' property is no longer available.
 *     - post-load: Callbacks registered in this group are applied directly
 *       after this library is loaded. At this point, the library contains a
 *       'loaded' key, which contains the number of files that were loaded.
 *   Additional top-level properties can be registered as needed.
 *
 * @see hook_library()
 */
function xml_field_codemirror_libraries_info() {
  // Expected to be extracted into 'sites/all/libraries/xml_field_codemirror'.
  $libraries['codemirror'] = array(
    'name' => 'CodeMirror',
    'vendor url' => 'http://codemirror.net/',
    'download url' => 'https://github.com/marijnh/CodeMirror/downloads',
    'version arguments' => array(
      'file' => 'lib/codemirror.js',
      'pattern' => '/version  ?([\d.]+)/',
      'lines' => 3,
    ),
    'files' => array(
      'js' => array(
        'lib/codemirror.js',
      ),
      'css' => array(
        'lib/codemirror.css',
      ),
    ),
  );
  return $libraries;
}
